version: "3.1"
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/application/
      - ./docker/php/php_ini_overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/20-xdebug.ini
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ff
      MYSQL_USER: qwerty
      MYSQL_PASSWORD: secret
    ports:
    - "3306:3306"
