version: "3.1"
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/application/
      - ./docker/php/php_ini_overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/20-xdebug.ini
    tty: true
