version: "3.1"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ../application:/application
      - ./nginx/:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    links:
      - php

  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    volumes:
      - ../application:/application
      - ./php/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      - ./php/xdebug.ini:/etc/php/7.3/fpm/conf.d/20-xdebug.ini
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: gobliN123
      MYSQL_DATABASE: mysite_wp
      MYSQL_USER: mysite_user
      MYSQL_PASSWORD: mypass
    ports:
    - "3306:3306"
